<?php

  function my_acf_add_local_field_groups() {
    acf_add_local_field_group([
      'key'    => 'group_629a2f42f31d8',
      'title'  => 'Footer',
      'fields' => [
        [
          'key'               => 'field_629a2f4f0738e',
          'label'             => 'Footer Logo',
          'name'              => 'footer_logo',
          'type'              => 'image',
          'instructions'      => '',
          'required'          => 0,
          'conditional_logic' => 0,
          'wrapper'           => [
            'width' => '',
            'class' => '',
            'id'    => '',
          ],
          'return_format' => 'id',
          'preview_size'  => 'medium',
          'library'       => 'all',
          'min_width'     => '',
          'min_height'    => '',
          'min_size'      => '',
          'max_width'     => '',
          'max_height'    => '',
          'max_size'      => '',
          'mime_types'    => '',
        ],
      ],
      'location' => [
        [
          [
            'param'    => 'options_page',
            'operator' => '==',
            'value'    => 'acf-options',
          ],
        ],
      ],
      'menu_order'            => 0,
      'position'              => 'normal',
      'style'                 => 'default',
      'label_placement'       => 'left',
      'instruction_placement' => 'label',
      'hide_on_screen'        => '',
      'active'                => true,
      'description'           => '',
      'show_in_rest'          => 0,
    ]);

    acf_add_local_field_group([
      'key'    => 'group_629a2dcc66acf',
      'title'  => 'Header',
      'fields' => [
        [
          'key'               => 'field_629a2ddc57447',
          'label'             => 'Header Logo Desktop',
          'name'              => 'header_logo_desktop',
          'type'              => 'image',
          'instructions'      => '',
          'required'          => 0,
          'conditional_logic' => 0,
          'wrapper'           => [
            'width' => '',
            'class' => '',
            'id'    => '',
          ],
          'return_format' => 'array',
          'preview_size'  => 'medium',
          'library'       => 'all',
          'min_width'     => '',
          'min_height'    => '',
          'min_size'      => '',
          'max_width'     => '',
          'max_height'    => '',
          'max_size'      => '',
          'mime_types'    => '',
        ],
      ],
      'location' => [
        [
          [
            'param'    => 'options_page',
            'operator' => '==',
            'value'    => 'acf-options',
          ],
        ],
      ],
      'menu_order'            => 0,
      'position'              => 'normal',
      'style'                 => 'default',
      'label_placement'       => 'left',
      'instruction_placement' => 'label',
      'hide_on_screen'        => '',
      'active'                => true,
      'description'           => '',
      'show_in_rest'          => 0,
    ]);

    acf_add_local_field_group([
      'key'    => 'group_629a2faa841fd',
      'title'  => 'Social Links',
      'fields' => [
        [
          'key'               => 'field_629a2fb777e36',
          'label'             => 'Facebook Link',
          'name'              => 'facebook_link',
          'type'              => 'url',
          'instructions'      => 'Leave blank to hide.',
          'required'          => 0,
          'conditional_logic' => 0,
          'wrapper'           => [
            'width' => '',
            'class' => '',
            'id'    => '',
          ],
          'default_value' => '',
          'placeholder'   => '',
        ],
        [
          'key'               => 'field_629a3063d54b8',
          'label'             => 'Twitter Link',
          'name'              => 'twitter_link',
          'type'              => 'url',
          'instructions'      => 'Leave blank to hide.',
          'required'          => 0,
          'conditional_logic' => 0,
          'wrapper'           => [
            'width' => '',
            'class' => '',
            'id'    => '',
          ],
          'default_value' => '',
          'placeholder'   => '',
        ],
        [
          'key'               => 'field_629a308052147',
          'label'             => 'Instagram Link',
          'name'              => 'instagram_link',
          'type'              => 'url',
          'instructions'      => 'Leave blank to hide.',
          'required'          => 0,
          'conditional_logic' => 0,
          'wrapper'           => [
            'width' => '',
            'class' => '',
            'id'    => '',
          ],
          'default_value' => '',
          'placeholder'   => '',
        ],
        [
          'key'               => 'field_629a309b3cadc',
          'label'             => 'LinkedIn Link',
          'name'              => 'linkedin_link',
          'type'              => 'url',
          'instructions'      => 'Leave blank to hide.',
          'required'          => 0,
          'conditional_logic' => 0,
          'wrapper'           => [
            'width' => '',
            'class' => '',
            'id'    => '',
          ],
          'default_value' => '',
          'placeholder'   => '',
        ],
        [
          'key'               => 'field_629a30b676ab7',
          'label'             => 'Pinterest Link',
          'name'              => 'pinterest_link',
          'type'              => 'url',
          'instructions'      => 'Leave blank to hide.',
          'required'          => 0,
          'conditional_logic' => 0,
          'wrapper'           => [
            'width' => '',
            'class' => '',
            'id'    => '',
          ],
          'default_value' => '',
          'placeholder'   => '',
        ],
        [
          'key'               => 'field_629a30cd8c388',
          'label'             => 'YouTube Link',
          'name'              => 'youtube_link',
          'type'              => 'url',
          'instructions'      => 'Leave blank to hide.',
          'required'          => 0,
          'conditional_logic' => 0,
          'wrapper'           => [
            'width' => '',
            'class' => '',
            'id'    => '',
          ],
          'default_value' => '',
          'placeholder'   => '',
        ],
      ],
      'location' => [
        [
          [
            'param'    => 'options_page',
            'operator' => '==',
            'value'    => 'acf-options',
          ],
        ],
      ],
      'menu_order'            => 0,
      'position'              => 'normal',
      'style'                 => 'default',
      'label_placement'       => 'left',
      'instruction_placement' => 'label',
      'hide_on_screen'        => '',
      'active'                => true,
      'description'           => '',
      'show_in_rest'          => 0,
    ]);
  }
  add_action('acf/init', 'my_acf_add_local_field_groups');
